######################################################################
# Automatically generated by qmake (3.1) Sun May 3 12:57:15 2020
######################################################################

TEMPLATE = app
TARGET = rmap
INCLUDEPATH += .

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

QT += gui widgets

# Input
FORMS += ui/config.ui ui/rmap.ui
HEADERS += src/RegMapTreeView.hpp \
           src/RegMapWindow.hpp \
           src/rmap.hpp
INCLUDEPATH += src
SOURCES += src/rmap.cpp \
           src/argparser.cpp \
           src/RegMapWindow.cpp \
           src/RegMapTreeView.cpp
RESOURCES += ui/resources.qrc
