######################################################################
# Automatically generated by qmake (3.1) Sun May 3 12:57:15 2020
######################################################################

TEMPLATE = app
TARGET = rmap
INCLUDEPATH += .

;CONFIG=release

DEFINES += QT_DEPRECATED_WARNINGS
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

QT += gui widgets

# Input
FORMS += ui/config.ui ui/rmap.ui
HEADERS += src/Serializable.hpp \
           src/SerializationContext.hpp \
           src/RegMapTreeItem.hpp \
           src/RegMapTreeModel.hpp \
           src/RegMapTreeView.hpp \
           src/RegMapWindow.hpp \
           src/RegMapDelegate.hpp \
           src/RegConfigWindow.hpp \
           src/rmap.hpp
INCLUDEPATH += src
SOURCES += src/SerializationContext.cpp \
           src/RegMapTreeItem.cpp \
           src/RegMapTreeModel.cpp \
           src/RegMapTreeView.cpp \
           src/RegMapWindow.cpp \
           src/RegMapDelegate.cpp \
           src/RegConfigWindow.cpp \
           src/rmap.cpp
RESOURCES += ui/resources.qrc

CONFIG(debug, debug|release) {
    DESTDIR = build/debug
} else {
    DESTDIR = build/release
}

release:DESTDIR = release
release:OBJECTS_DIR = release/.obj
release:MOC_DIR = release/.moc
release:RCC_DIR = release/.rcc
release:UI_DIR = release/.ui

debug:DESTDIR = debug
debug:OBJECTS_DIR = debug/.obj
debug:MOC_DIR = debug/.moc
debug:RCC_DIR = debug/.rcc
debug:UI_DIR = debug/.ui
