syntax = "proto3";

package protormap;

import "google/protobuf/timestamp.proto";

message Config {
    enum FileType {
        TEXT = 0;
        BINARY = 1;
    }
    FileType filetype   = 1;
    string pythonScript = 2;
}

message RegItem {
    enum Kind {
        ROOT = 0;
        BLK  = 1;
        REG  = 2;
        FLD  = 3;
        MEM  = 4;
        MAP  = 5;
    }
    uint32          id           = 1;
    repeated uint32 child_id     = 2;
    Kind            kind         = 3;
    map<string, string> itemData = 4;
}

message RegModel {

    Config config = 1;
    repeated RegItem item   = 2;
    google.protobuf.Timestamp last_updated = 3;
}
