syntax = "proto3";

package protormap;

import "google/protobuf/timestamp.proto";

message Config {
    enum FileType {
        TEXT = 0;
        BINARY = 1;
    }
    FileType filetype   = 1;
    string pythonScript = 2;
}

message RegItem {
    enum Kind {
        ROOT = 0;
        BLK  = 1;
        REG  = 2;
        FLD  = 3;
        MEM  = 4;
        MAP  = 5;
    }
    uint32 id          = 1;
    Kind   kind        = 2;
    string offset      = 3;
    string size        = 4;
    string name        = 5;
    string description = 6;
}

message RegModel {

    Config config = 1;
    repeated RegItem item   = 2;
    google.protobuf.Timestamp last_updated = 3;
}
