//Agnisys, Inc. ***** Copyright 2014 All Rights Reserved. *****
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// created by        : Alves, Ezequiel
// generated by      : ealves
// generated from    : Z:\330301\git-mirror\digital\docs\spec\regmap\direct_regmap.docx
// IDesignSpec rev   : 6.4.8.0
// XML Revision      : $Revision: 1.154 $

//*** This code is generated with following settings ***
// Reg Width                  : 32
// Address Unit               : 32
// C++ Types int              : hwint
// Bus Type                   : PROPRIETARY
// BigEndian                  : true
// LittleEndian               : true
// Dist. Decode and Readback  : false
//---------------------------------------------------------------------------------------------------------------



`ifndef DIRECT_REGMAP_REGMEM
`define DIRECT_REGMAP_REGMEM

package direct_regmap_regmem_pkg;
    import uvm_pkg::*;
    `include "uvm_macros.svh"
    
    
    `include "direct_regmap.regmem.sv"
    
endpackage
`endif

